### ISSUE TITLE
release-v1.0.0-rc.3  example: cartrade

### ISSUE THREAD

**Issue by Virus-Syl** [hyperledger/cactus#1898] opened 2022-03-07 06:32 UTC
when I run : npm run build
result:

> build
> npm run build-ts && npm run copy-static-assets && npm run copy-blp-config && npm run replace-blp-config-path

> build-ts
> tsc -p ./tsconfig.json

BusinessLogicCartrade.ts:282:39 - error TS2345: Argument of type '{ type: string; }' is not assignable to parameter of type '{ command: string; }'.
  Property 'command' is missing in type '{ type: string; }' but required in type '{ command: string; }'.

282           .sendAsyncRequest(contract, method, args)
                                          ~~~~~~

  ../../packages/cactus-cmd-socketio-server/src/main/typescript/verifier/Verifier.ts:83:15
    83     method: { command: string },
                     ~~~~~~~
    'command' is declared here.

TemplateTradeManagement.ts:97:35 - error TS2345: Argument of type '{}' is not assignable to parameter of type '{ command: string; }'.
  Property 'command' is missing in type '{}' but required in type '{ command: string; }'.

97       .sendAsyncRequest(contract, method, args)
                                     ~~~~~~

  ../../packages/cactus-cmd-socketio-server/src/main/typescript/verifier/Verifier.ts:83:15
    83     method: { command: string },
                     ~~~~~~~
    'command' is declared here.

Found 2 errors.

**Comment by outSH** [comment] 2022-03-07 09:04
`cartrade` will be removed from next release because it duplicates `discounted-cartrade` logic. As for the issue, it was fixed on `main` branch some time ago (before it was removed), you can checkout this commit for working sample app - `a8734bf0c6f8ab1723cfab50a14eab44d282f3a9`.

**Comment by petermetz** [comment] 2022-03-23 21:20
@Virus-Syl If you could confirm whether the above helped or not please do so and then we can potentially close the issue based on your feedback (if it was resolved). Otherwise let's talk more about what the problem is.

**Comment by petermetz** [comment] 2022-04-12 19:31
@outSH @Virus-Syl Closing due to inactivity. Feel free to reopen anytime of course.

**Closed by petermetz** 2022-04-12 19:31 UTC
Labels: bug
