### ISSUE TITLE
Latest whitepaper in pdf

### ISSUE THREAD

**Issue by brunob15** [hyperledger/cactus#254] opened 2020-08-12 12:25 UTC
Hi all, does anyone have the latest version of the whitepaper in pdf? I'm not being able to find or generate it.

Thanks.

**Comment by petermetz** [comment] 2020-08-14 04:44
Hi @brunob15 you can run `make pdf` while in the `./whitepaper` directory, but it's only been tested on Ubuntu 18,20 so far. We are working on the automation so that each commit triggers a re-build and publish the pdf to a dedicated documentation site, but it's not ready yet. The formatting of the .pdf is also not perfect yet, so for now IMO your best bet is to just scroll through the markdown file via the GitHub UI.

**Comment by petermetz** [comment] 2020-08-14 04:44
Closing as duplicate of https://github.com/hyperledger/cactus/issues/157

**Closed by petermetz** 2020-08-14 04:44 UTC
Labels: duplicate

**Comment by brunob15** [comment] 2020-08-14 10:43
Thanks @petermetz!

I finally ended up converting the markdown to pdf using this npm package: https://www.npmjs.com/package/md-to-pdf

**Comment by petermetz** [comment] 2020-08-14 16:37
> Thanks @petermetz!
> 
> I finally ended up converting the markdown to pdf using this npm package: https://www.npmjs.com/package/md-to-pdf

Is the formatting of it decent enough? If that package works cross-platform we should probably migrate over to it and ditch the current tool-chain of the whitepaper.
